version: 2
jobs:
  build:
    docker:
      - image: casimir/python-circleci-rsync
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: build and deploy
          command: |
            . venv/bin/activate
            ssh-keyscan -H data.etalab.studio >> ~/.ssh/known_hosts
            lektor build && lektor deploy studio
    branches:
      only:
        - master
